FORMAT: 1A

# Our People Conference API

API to expose our people conference functionality.

# Group Public endpoints

## Discussions [/ourpeopleconference/discussions]

### Create a Discussion request [POST]

My Development application will use this endpoint to notify OPC that an employee wants to be discussed from within a talk.

+ Request (application/json)
    + Headers

            Accept-Charset: utf-8
            Authentication: Bearer {{token}}
            X-FORWARDED-HOST: {{host}}
            X-AUTH-TENANT: {{customer}}
    + Body
    + Attributes (Discussion)

+ Response 201 (application/hal+json)
    + Body
    + Attributes (Discussion Created)


# Group Events

## Discussion Updated [/haufe-umantis.opc.v1.cqrs.discussion.updated]
+ **Description**
    + **id**: Id of the discussion
    + **name**: Name of the conference
    + **initiated_by**: Name of the person who initiated the discussion (applies only to status COMPLETED)
    + **status**: Status of the discusion
    + **comments**: Optional comment of the discussion (applies only to status COMPLETED)
    + **link**: Link to retrieve an updated representation of the resource
    
+ Attributes (Discussion)
    + id: 1 (number, required)
    + name: Conference Name (string, required)
    + initiated_by: John Doe (string, required)
    + status: COMPLETED (enum[string], required)
    + comments: The employee must train its leadership skill before moving up (string, optional)
    + link: `http://localhost:8080/ourpeopleconference/v1/discussions/1` (string, required)

### TOPIC: haufe-umantis.opc.v1.cqrs.discussion.update  [GET /haufe-umantis.opc.v1.cqrs.discussion.update]

#### A discussion was updated
- When a discussion request is assigned to a conference, an update event is raised notifying it. The status specified on this event must be ADDED.
- When a discussion is completed to a conference, an update event is raised notifying it. The status specified on this event must be COMPLETED. Additionally field initiated_by must be filled and comments could be filled.

+ Request (application/json)

+ Response 200 (application/json)
    + Headers
    + Body
    + Attributes (Discussion Event)



# Data Structures

## Event Headers
+ type: cqrs (enum, required)
    + notification
    + cqrs
+ resource: Discussion (string, optional)
+ secured: false (boolean, required)
+ origin: opc (string, optional)
+ customer: 1111 (string, required)

## Discussion
+ user: `a9b7ba70-783b-317e-9998-dc4dd82eb3c5` (string, required)
+ reason: TIME_IN_POSITION (enum[string], required)
    + TIME_IN_POSITION
    + REINTEGRATION
    + REQUEST_BY_EMPLOYEE
+ needed_by: EMPLOYEE (enum[string], required)
    + EMPLOYEE
    + HR
    + MANAGER
+ question: I'd like to move within the company. (string, required)

## Discussion Created (Discussion)
+ id: 1 (number, required)
+ status: NEW (enum[string], required)
+ self
    + href: `http://localhost:8080/ourpeopleconference/v1/discussions/1` (string, required)

## Discussion Event (Discussion)
+ headers (Event Headers, required)
+ id: 1 (number, required)
+ name: Conference Name (string, required)
+ status: COMPLETED (enum[string], required)
+ date: `2017-06-20T12:20:29.147+0000` (string, required)
+ comments: The employee must train its leadership skill before moving up (string, optional)
+ link: `http://localhost:8080/ourpeopleconference/v1/discussions/1` (string, required)